services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - litellm-net

  litellm:
    image: ghcr.io/berriai/litellm-database:main-latest
    container_name: litellm
    ports:
      - "4000:4000"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./.env:/app/.env
    env_file:
      - .env
    command: --config /app/config.yaml
    depends_on:
      - qdrant
      - postgres
    networks:
      - litellm-net

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - litellm-net

volumes:
  postgres_data:
  qdrant_data:

networks:
  litellm-net:
    driver: bridge